#Specify a base image 
FROM node:16-alpine

USER root 

WORKDIR /app/

# Install package.json which is needed for npm install - no change in package.json so the npm install won't be rebuild again
COPY ./package.json ./
RUN npm install

#here a change will be detected(in index.js)
COPY ./ ./

#Default command
CMD ["npm","run","start"]